### ISSUE TITLE
这就是你们支持的国产软件notepad--，才几天已经开始割韭菜了。

### ISSUE THREAD

**Issue by tonyqus** [Nick-DL/nick-dl.github.io#3]
你说一个免费软件为啥要用注册码？又要叫免费永久试用版本？
![9f825f8cdda57511e0ffa0b50eed9a0](https://user-images.githubusercontent.com/772561/216768054-a054de25-bb7c-4153-9380-f0c5b712b7cd.png)

![ee7e79d839ed15e349a157f3df050d9](https://user-images.githubusercontent.com/772561/216768044-ba053d31-f221-4edd-a08c-11c59e2df9f9.png)

**Comment by Nick-DL** [comment]
你说的我不敢苟同。想捐助支持是用户自己的事，支持哪款软件也是可以选择的。捐助本身是没有问题的，这款软件也没有因为免费用户而限制主要功能，我只能说在捐助这一点上它没有太大的错误。（当然如果其代码主要都是借用来的话这确实不太正常，但事实应该不是这样的。我很少用到这一类软件，对这方面不太清楚。）

另外，任何人做的事都有被他人批评的权利，就像我们讨论N++的政治观点一样。所以您对这个APP割韭菜行为的批评没有任何问题。另外，我们讨论的其实没有什么意义，如果批评不会被当事人接受的话，我们都只能算“无聊的看客”。所以我真心希望这些讨论就此为止。

另外，感谢您对我的一些指点，包括之前的和现在的；相信我能从中有所领悟。就这样吧，希望我现在看到你的留言不算很晚。

**Comment by Nick-DL** [comment]
另外，唐他的举动我其实一直不能理解。npp已经在国内非常出名了，我很早以前就已经试用过，它在我的PE启动U盘里也是一直起到记事本的作用的。他一直的举动我只能认为就是简单的宣扬与造势，如此出名的开源软件不需要他这种举动来达到“完全的普及”，如果他不做这些事情，这个软件也根本不会被抨击（即使现在也只是有人🐴，再把他的网站向有关平台举报一下而已，这软件没有被实际地禁止）。总之我认为实际的情况和他想的不太一样

**Comment by tonyqus** [comment]
感谢解锁这个issue，我说下我的观点。

首先我不是"无聊的看客"，我用npp很多年了，算是老用户。基本上npp是我每次装机必备的软件，而且我只从github下载安装包，原因是国内的下载网站90%都有木马（说90%都是客气的），我实在不敢去下那种安装包，太恐怖了，装完机器直接变木马机。对于这款软件我是一直很感恩的，因为它让我的设备远离病毒，这是非常重要的，经过这么多年的观察（我用过很多npp版本），作者已经建立了足够的信用机制，也并不会因为一句玩笑而完全摧毁他的信用。开源的精髓很多时候是信任，这和国内的开源社区环境完全不同，我说这句话是因为我也是开源老兵，我很清楚国内做开源有多难做。

当然作者确实嘴很大，这点我不否认，所以我也认同你说的：
`如果他不做这些事情，这个软件也根本不会被抨击（即使现在也只是有人🐴，再把他的网站向有关平台举报一下而已，这软件没有被实际地禁止）。
`

但我不认同你说的他是为了宣扬和造势，如果哪一天你也做一个开源软件能做到npp这样，你就会明白为什么不需要造势。你看看下面的Stackoverflow 2022开发者调查排名就懂了。
![image](https://user-images.githubusercontent.com/772561/216842575-abd0e42a-748c-4425-b4b1-488c5ab2803c.png)

你说一个全球排名前四的编辑器/IDE需要造势吗？而且前面3个都是商业软体，是公司雇人开发的，只有npp是社区/个人开源项目。所以它并不是只在中国出名，而是因为它全球都很出名，所以你才会知道并安装npp。

从我的角度看，npp作者并不需要造势，而是作者在行使自己的言论自由权力，可能你还小，又在国内长大，不太能理解，其实国外抨击政党和国家元首是很常见的事，且每个人都有和平表达自己观点的权利，如果你把作者在release上加上标语的行为理解成一次和平的游行，你是不是更容易接受一些？

但你既然可以翻墙，不如去google搜一下npp作者所列出的所有标语的出处，以及他所要表达的观点是什么？是不是就是他一个人这么说？说的那些人是不是都是反华势力？还是说其实也不一定。

但我基本上是把政治观点和软件本身分得很开，我觉得他表达任何观点是他的权力，他的软件好和他嘴大没有半毛钱关系。

**Comment by tonyqus** [comment]
最后祝中考考出好成绩，有条件的话以后可以出国留学。

在你这个年龄能够接触github这样的开源社区是非常好的，你比别人拥有独特的unfair advantage，但你必须学会融入开源社区才能从中受益，这个过程我也用了接近十年的时间才融入全球开源社区，所以慢慢来。

**Comment by Nick-DL** [comment]
解锁是我误点的，别误会😂
谢谢您对我的祝福
最后，这事大概是与我无关了，最近的风波也快消停了，我不会再关注了...

**Comment by Nick-DL** [comment]
🔒那个是误点的，您别误会哈😂。

> 原因是国内的下载网站90%都有木马（说90%都是客气的），我实在不敢去下那种安装包，太恐怖了，装完机器直接变木马机。

这点我确实没有体会到。他为我们用上干净的软件帮了大忙，但我觉得真是有些小题大做。或者说，一部分人不能理解。

国内用户对病毒这些可是麻木的，真正想自己电脑有“强迫症”一般干净的人可能就不到5%。或者还有一种可能，现在国内用npp的人有一半就已经不会再光顾下载站了，他们知道如何获取原版。

从这个角度来说，npp作者想推广这开源软件，应该打好口碑，成立中文官网或找他人帮忙建站分发，再弄到搜索引擎上作为官方网站。不过我承认现在国内网络环境比我们都想的复杂的多，他之所以曲折绕远，是因为他已经发过让我们不满的政治言论，没办法了？这实在是太离谱了，从来没有这样听说过这样的软件吧。

> 作者已经建立了足够的信用机制，也并不会因为一句玩笑而完全摧毁他的信用。开源的精髓很多时候是信任，这和国内的开源社区环境完全不同，我说这句话是因为我也是开源老兵，我很清楚国内做开源有多难做。

这一点确实可以想象的出来，但他说的“随机字符”对于国内不了解他的人来说真的是败坏仅有的一点点“信任”，谁知道他说的是不是真的呢。。所以可以看出他对大陆用户真的是无所谓。~~但是多数用户真的会对作者自己的事有这么深入的了解嘛？国内对他了解不够的，很容易产生抵制npp的想法，他为了自己的政治追求真是不要国内口碑了（他觉得无所谓吧但又再想在国内推广npp，？？）。这属实是他行事有点不稳重了，多数人就算有想法也会尽力避免对自己的职业名声什么的产生影响，他这么弄，真就很像个跳梁小丑啊。~~`这些话思绪混乱，别看`

另外，排除对其政治观点的看法，我也只会觉得他就是个糟老头子😂。你能想象看到一个半头白发的人上P站对着屏幕____的那种感觉吗。我会觉得这样不好哈哈。

最后，谢谢您对我的祝福。

**Comment by Nick-DL** [comment]
感觉“民族主义”“爱国主义”常常被西方人和“西方人”误解。其实但凡存在一个民族（美利坚全体人民也可以组成这样一个民族），一个国家，这种将自己的所在从卑微向强大发展的心思，本质上都是一样的，所以都可以被这么叫。农耕文明嘲笑海洋文明的“自由”，海洋文明嘲笑农耕文明的“束缚”。这一点不能被打破，我们的讨论都是没啥意思的。

最近看到我喜爱的电影《流浪地球2》被西方媒体批评，他们常常将电影的败笔归结为nationalism，是可以说明他们对中国始终有些执念。明明是表达了呼吁人们团结共赢的主题的电影，被这么一误读，实在是不知道该怎么说（关键是球2里没有这个思想。。）。

这种观念和侯的非常像，我不知道他对我们这里到底有多少认知。但我几乎可以确定，他不太懂。再次扯回到前面的话，他输出过一堆话，觉得自己的软件已经被大陆封杀，其实他的所作所为只是上过短视频和小站新闻，他的软件没有受影响，对我们没什么影响🐶

最后是球2里的量子AI计算机MOSS的话：

> （MOSS 制造过多次危机是）为了克服人类对历史、当下、未来的执念。

感觉我想的太多了哈哈。这些话不是针对开源软件的🙃

**Comment by tonyqus** [comment]
npp作者是2000年本科毕业，也就40多岁，并没有你说的那么老，我理解他和你爹的年龄差不多。

你可能不太了解美国人，美国人就是不太爱国的，没事就骂自己的国家、政党、总统，这是日常，和我们的爱国教育不太一样，所以人家的民族主义要弱很多，当然不是说完全没有。而且美国是移民国家，多民族多肤色人种混居，推"美国民族“这种概念也行不通啊。
